CREATE TYPE "public"."activity_type" AS ENUM('buy', 'sell', 'liquidity_add', 'liquidity_remove', 'token_create', 'pool_create', 'transfer', 'swap', 'bridge', 'stake');--> statement-breakpoint
CREATE TYPE "public"."archetype" AS ENUM('significant_entry', 'community_convergence', 'early_discovery', 'large_movement', 'token_momentum', 'network_activity');--> statement-breakpoint
CREATE TABLE "activities" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"signature" text NOT NULL,
	"wallet" text NOT NULL,
	"token_mint" text,
	"type" "activity_type" NOT NULL,
	"amount" numeric,
	"value_usd" numeric,
	"timestamp" timestamp with time zone NOT NULL,
	"slot" bigint,
	"meta" jsonb,
	"event_created" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "activities_signature_unique" UNIQUE("signature")
);
--> statement-breakpoint
CREATE TABLE "claim_challenges" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"wallet" text NOT NULL,
	"nonce" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "follows" (
	"follower_wallet" text NOT NULL,
	"followee_wallet" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "follows_follower_wallet_followee_wallet_pk" PRIMARY KEY("follower_wallet","followee_wallet")
);
--> statement-breakpoint
CREATE TABLE "social_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "social_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"archetype" "archetype" NOT NULL,
	"wallet" text,
	"token_mint" text,
	"source_activity_ids" bigint[] DEFAULT '{}' NOT NULL,
	"significance" numeric DEFAULT '0' NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "token_stats" (
	"mint" text NOT NULL,
	"sampled_at" timestamp with time zone NOT NULL,
	"holder_count" bigint DEFAULT 0 NOT NULL,
	"volume_24h" numeric,
	"buyers_1h" integer DEFAULT 0 NOT NULL,
	"sellers_1h" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "token_stats_mint_sampled_at_pk" PRIMARY KEY("mint","sampled_at")
);
--> statement-breakpoint
CREATE TABLE "tokens" (
	"mint" text PRIMARY KEY NOT NULL,
	"symbol" text,
	"name" text,
	"decimals" integer DEFAULT 0 NOT NULL,
	"price_usd" numeric,
	"market_cap" numeric,
	"holder_count" bigint DEFAULT 0 NOT NULL,
	"volume_24h" numeric,
	"first_observed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"wallet_address" text NOT NULL,
	"username" text NOT NULL,
	"claimed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_wallet_address_unique" UNIQUE("wallet_address"),
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "wallets" (
	"address" text PRIMARY KEY NOT NULL,
	"first_observed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_activity_at" timestamp with time zone,
	"tx_count" bigint DEFAULT 0 NOT NULL,
	"token_interactions" bigint DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "watches" (
	"wallet_address" text NOT NULL,
	"token_mint" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "watches_wallet_address_token_mint_pk" PRIMARY KEY("wallet_address","token_mint")
);
--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_wallet_wallets_address_fk" FOREIGN KEY ("wallet") REFERENCES "public"."wallets"("address") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_token_mint_tokens_mint_fk" FOREIGN KEY ("token_mint") REFERENCES "public"."tokens"("mint") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follows" ADD CONSTRAINT "follows_follower_wallet_wallets_address_fk" FOREIGN KEY ("follower_wallet") REFERENCES "public"."wallets"("address") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follows" ADD CONSTRAINT "follows_followee_wallet_wallets_address_fk" FOREIGN KEY ("followee_wallet") REFERENCES "public"."wallets"("address") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "social_events" ADD CONSTRAINT "social_events_wallet_wallets_address_fk" FOREIGN KEY ("wallet") REFERENCES "public"."wallets"("address") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "social_events" ADD CONSTRAINT "social_events_token_mint_tokens_mint_fk" FOREIGN KEY ("token_mint") REFERENCES "public"."tokens"("mint") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "token_stats" ADD CONSTRAINT "token_stats_mint_tokens_mint_fk" FOREIGN KEY ("mint") REFERENCES "public"."tokens"("mint") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_wallet_address_wallets_address_fk" FOREIGN KEY ("wallet_address") REFERENCES "public"."wallets"("address") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watches" ADD CONSTRAINT "watches_wallet_address_wallets_address_fk" FOREIGN KEY ("wallet_address") REFERENCES "public"."wallets"("address") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "activities_wallet_idx" ON "activities" USING btree ("wallet");--> statement-breakpoint
CREATE INDEX "activities_token_idx" ON "activities" USING btree ("token_mint");--> statement-breakpoint
CREATE INDEX "activities_timestamp_idx" ON "activities" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "claim_challenges_wallet_idx" ON "claim_challenges" USING btree ("wallet");--> statement-breakpoint
CREATE INDEX "follows_followee_idx" ON "follows" USING btree ("followee_wallet");--> statement-breakpoint
CREATE INDEX "social_events_created_idx" ON "social_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "social_events_wallet_idx" ON "social_events" USING btree ("wallet");--> statement-breakpoint
CREATE INDEX "social_events_token_idx" ON "social_events" USING btree ("token_mint");--> statement-breakpoint
CREATE INDEX "token_stats_mint_idx" ON "token_stats" USING btree ("mint");--> statement-breakpoint
CREATE INDEX "wallets_last_activity_idx" ON "wallets" USING btree ("last_activity_at");--> statement-breakpoint
CREATE INDEX "watches_token_idx" ON "watches" USING btree ("token_mint");